data:
  train: "train_grid_data.jld"
  test: "test_grid_data.jld"

batch_size: 2
test_batch_size: 2
lr: 0.0001

node_embedding_size: 64
edge_embedding_size: 8
node_hidden_size: 128
node_output_size: 16

max_prev_node: 6
max_num_node: 25

resume_from: 1

epochs: 100

auto_resume:
  enable: False
  checkpointsdir: "checkpoints"
  save_model: 10
  model_path: "" # If model path is provided, checkpoint dir is ignored.

eval_period: 1

TBlog:
  enable: True
  log_dir: "logs"
  img_log_period: 1
  img_tag: "Test Images"

  train_loss_tag: "Training/Loss"

  test_loss_log_period: 1
  test_loss_tag: "Testing/Loss"
