data:
  train: "train_sbm_data.jld"
  test: "test_sbm_data.jld"

batch_size: 2
test_batch_size: 2
lr: 0.0001

node_embedding_size: 64
edge_embedding_size: 8
node_hidden_size: 128
node_output_size: 16

max_prev_node: 135
max_num_node: 160

resume_from: 1

epochs: 100

auto_resume: 
  enable: True
  checkpointsdir: "checkpoints"
  model_path: "" # If model path is provided, checkpoint dir is ignored. 
model_path: # Add model path here
tensorboard:
  enable: True
  log_dir: "logs"